services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20

  logger:
    build: ./logger
    ports:
      - "9000:9000"
    volumes:
      - logs:/logs
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:9000/health"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: appdb
      DB_USER: appuser
      DB_PASSWORD: apppassword
      LOGGER_URL: http://logger:9000/log
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
      logger:
        condition: service_healthy

  frontend:
    build: ./frontend
    environment:
      BACKEND_URL: http://backend:5000/api/data
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_started

volumes:
  pgdata:
  logs:
